KS-1-5 lesson one, task five
Sergey-Chesnokov/KotlinSprint pull request #5
Opened 2024-12-22 15:01 UTC by Sergey-Chesnokov

2024-12-23 07:14 UTC, ievetrovdev requested changes

2024-12-23 07:14 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/task_5.kt
> +    var HOURS = 3600 // 3600 секунд в часе
Название для константы правильно написано, только у тебя это не константа, а обычна переменная. Не хватает ключевого слова const. Так же когда есть возможно использовать неизменяемые переменные (val), нужно их использовать

2024-12-23 07:14 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/task_5.kt
> +    var flightTimeOfTheSeconds = seconds % 60 // остаток в секундах который не поместился в минутах
выше же уже есть 60 виде переменной

2024-12-23 18:07 UTC, Sergey-Chesnokov commented on src/main/kotlin/lesson_1/task_5.kt
> +    var HOURS = 3600 // 3600 секунд в часе
все правильно делал, зачем я в 5-ом задании "изменяемых" натыкал, сам не понял

2024-12-23 18:42 UTC, Sergey-Chesnokov commented on src/main/kotlin/lesson_1/task_5.kt
> +    var HOURS = 3600 // 3600 секунд в часе
Исправил, добавил константы, код сократился, воспользовался значением MINUTE для деление на остаток от 60-ти

2024-12-23 18:44 UTC, Sergey-Chesnokov commented on src/main/kotlin/lesson_1/task_5.kt
> +    var flightTimeOfTheSeconds = seconds % 60 // остаток в секундах который не поместился в минутах
package org.example.lesson_1

fun main() {
    val seconds: Short = 6480
    val flightTimeOfTheHours = seconds / HOURS
    val flightTimeOfTheMinutes = (seconds % HOURS) / MINUTE // (остаток от деления общего количсетва секунд на количество секунд в часе) разделить на количество сикунд в минту
    val flightTimeOfTheSeconds = seconds % MINUTE // остаток в секундах который не поместился в минутах

    val flightTime = String.format("%02d:%02d:%02d", flightTimeOfTheHours, flightTimeOfTheMinutes, flightTimeOfTheSeconds)

    println(flightTime)
}

const val  HOURS = 3600 // 3600 секунд в часе
const val MINUTE = 60 // секунд в минуте

2024-12-23 18:45 UTC, Sergey-Chesnokov commented on src/main/kotlin/lesson_1/task_5.kt
> +    var flightTimeOfTheSeconds = seconds % 60 // остаток в секундах который не поместился в минутах
константу MINUTE я тоже вынес

2024-12-25 07:19 UTC, ievetrovdev approved these changes

2024-12-25 15:48 UTC, merged